/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WeekSixLab;

/**
 *
 * @author jesse
 */
public class LibraryGUI extends javax.swing.JFrame {

    Library library;
    
    /**
     * Creates new form LibraryGUI
     */
    public LibraryGUI() {
        Book twoTowers = new Book("twoTowers", "J.RR");
        Book learnJava17 = new Book("learnJava17", "Nick Samoylov");
        Book thePrince = new Book("thePrince", "machiavelli");
        Book Bible = new Book("Bible", "God");
        Book kingLear = new Book("kingLear", "Bill");
        Book greatGatsby = new Book("greatGatsby", "F.Scot");
        Book[] allBooks = {twoTowers, learnJava17, thePrince, Bible, kingLear, greatGatsby};
        library = new Library(allBooks);
        initComponents();
        NumBook.setText(Integer.toString(library.countAvailableBooks()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        BooksBorrw = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtSearchTi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtSearchAu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnBorrw = new javax.swing.JButton();
        TextRe = new javax.swing.JTextField();
        TxtBorrw = new javax.swing.JTextField();
        BtnRe = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        NumBook = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaList = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        BooksBorrw2 = new javax.swing.JTextArea();
        SearchTiResult = new javax.swing.JLabel();
        BtnSearchTi = new javax.swing.JButton();
        BtnSearchAu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TxtTi = new javax.swing.JTextField();
        TxtAu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnAddBook = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtAreaAu = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jComboBox1.setBackground(new java.awt.Color(0, 0, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Search");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField5.setText("jTextField5");

        BooksBorrw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BooksBorrw.setForeground(new java.awt.Color(0, 0, 0));
        BooksBorrw.setText("string");

        jLabel8.setBackground(new java.awt.Color(0, 0, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("string");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LIBRARY");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Search for books");

        TxtSearchTi.setBackground(new java.awt.Color(255, 255, 255));
        TxtSearchTi.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("By title");

        TxtSearchAu.setBackground(new java.awt.Color(255, 255, 255));
        TxtSearchAu.setForeground(new java.awt.Color(0, 0, 0));
        TxtSearchAu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSearchAuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("By author");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Borrow book");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Return book");

        BtnBorrw.setBackground(new java.awt.Color(0, 0, 204));
        BtnBorrw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnBorrw.setForeground(new java.awt.Color(255, 255, 255));
        BtnBorrw.setText("Borrow");
        BtnBorrw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBorrwMouseClicked(evt);
            }
        });

        TextRe.setBackground(new java.awt.Color(255, 255, 255));
        TextRe.setForeground(new java.awt.Color(0, 0, 0));

        TxtBorrw.setBackground(new java.awt.Color(255, 255, 255));
        TxtBorrw.setForeground(new java.awt.Color(0, 0, 0));

        BtnRe.setBackground(new java.awt.Color(0, 0, 204));
        BtnRe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRe.setForeground(new java.awt.Color(255, 255, 255));
        BtnRe.setText("Return");
        BtnRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnReMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Number of books in Library:");

        NumBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NumBook.setForeground(new java.awt.Color(0, 0, 0));
        NumBook.setText("num");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Books you have borrowed:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("List of books in the Library:");

        TxtAreaList.setBackground(new java.awt.Color(255, 255, 255));
        TxtAreaList.setColumns(20);
        TxtAreaList.setForeground(new java.awt.Color(0, 0, 0));
        TxtAreaList.setRows(5);
        TxtAreaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtAreaListMouseEntered(evt);
            }
        });
        TxtAreaList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAreaListKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(TxtAreaList);

        BooksBorrw2.setBackground(new java.awt.Color(255, 255, 255));
        BooksBorrw2.setColumns(20);
        BooksBorrw2.setForeground(new java.awt.Color(0, 0, 0));
        BooksBorrw2.setRows(5);
        jScrollPane3.setViewportView(BooksBorrw2);

        SearchTiResult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchTiResult.setForeground(new java.awt.Color(0, 0, 0));
        SearchTiResult.setText("string");

        BtnSearchTi.setBackground(new java.awt.Color(0, 0, 204));
        BtnSearchTi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSearchTi.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearchTi.setText("Search");
        BtnSearchTi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSearchTiMouseClicked(evt);
            }
        });

        BtnSearchAu.setBackground(new java.awt.Color(0, 0, 204));
        BtnSearchAu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSearchAu.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearchAu.setText("Search");
        BtnSearchAu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSearchAuMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Add books");

        TxtTi.setBackground(new java.awt.Color(255, 255, 255));
        TxtTi.setForeground(new java.awt.Color(0, 0, 0));

        TxtAu.setBackground(new java.awt.Color(255, 255, 255));
        TxtAu.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setBackground(new java.awt.Color(0, 0, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Title");

        jLabel13.setBackground(new java.awt.Color(0, 0, 204));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Author");

        BtnAddBook.setBackground(new java.awt.Color(0, 0, 204));
        BtnAddBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAddBook.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddBook.setText("Add");
        BtnAddBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddBookMouseClicked(evt);
            }
        });

        TxtAreaAu.setBackground(new java.awt.Color(255, 255, 255));
        TxtAreaAu.setColumns(20);
        TxtAreaAu.setForeground(new java.awt.Color(0, 0, 0));
        TxtAreaAu.setRows(5);
        jScrollPane4.setViewportView(TxtAreaAu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(TxtTi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(TxtAu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAddBook)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBorrw, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(BtnBorrw))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(TextRe, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRe))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(NumBook)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(TxtSearchTi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSearchTi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchTiResult, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtSearchAu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSearchAu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(220, 220, 220))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TextRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRe))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(NumBook)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtSearchTi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(BtnBorrw)
                            .addComponent(TxtBorrw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchTiResult)
                            .addComponent(BtnSearchTi))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtSearchAu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnSearchAu))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtTi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAddBook))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtSearchAuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSearchAuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSearchAuActionPerformed

    private void BtnBorrwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBorrwMouseClicked
        // TODO add your handling code here:
        if (! TxtBorrw.getText().equals("")) {
            library.borrowBookL(TxtBorrw.getText()); 
            BooksBorrw2.setText(library.findBorrowed());
            TxtBorrw.setText("");
    }
        
    }//GEN-LAST:event_BtnBorrwMouseClicked

    private void TxtAreaListKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAreaListKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtAreaListKeyTyped

    private void TxtAreaListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtAreaListMouseEntered
        // TODO add your handling code here:
        TxtAreaList.setText(library.listBooks());
    }//GEN-LAST:event_TxtAreaListMouseEntered

    private void BtnReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnReMouseClicked
        // TODO add your handling code here:
        if (! TextRe.getText().equals("")) {
            library.returnBookL(TextRe.getText());
            BooksBorrw2.setText(library.findBorrowed());
            TextRe.setText("");
            
        } 
    }//GEN-LAST:event_BtnReMouseClicked

    private void BtnSearchTiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSearchTiMouseClicked
        // TODO add your handling code here:
        if (! TxtSearchTi.getText().equals("")) {
            SearchTiResult.setText(library.searchByTitle(TxtSearchTi.getText()));
            TxtSearchTi.setText("");
        }
        
    }//GEN-LAST:event_BtnSearchTiMouseClicked

    private void BtnAddBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddBookMouseClicked
        // TODO add your handling code here:
        if (! TxtTi.getText().equals("") && ! TxtAu.getText().equals("")) {
            Book newbook = new Book(TxtTi.getText(), TxtAu.getText());
            library.addBook(newbook);
            TxtTi.setText("");
            TxtAu.setText("");
            NumBook.setText(Integer.toString(library.countAvailableBooks()));
            
        }
    }//GEN-LAST:event_BtnAddBookMouseClicked

    private void BtnSearchAuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSearchAuMouseClicked
        // TODO add your handling code here:
        if (! TxtSearchAu.getText().equals("")) {
            String theBooks = String.join(" ", library.searchByAuthor(TxtSearchAu.getText()));
            TxtAreaAu.setText(theBooks);
            TxtSearchAu.setText("");
        }
    }//GEN-LAST:event_BtnSearchAuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BooksBorrw;
    private javax.swing.JTextArea BooksBorrw2;
    private javax.swing.JButton BtnAddBook;
    private javax.swing.JButton BtnBorrw;
    private javax.swing.JButton BtnRe;
    private javax.swing.JButton BtnSearchAu;
    private javax.swing.JButton BtnSearchTi;
    private javax.swing.JLabel NumBook;
    private javax.swing.JLabel SearchTiResult;
    private javax.swing.JTextField TextRe;
    private javax.swing.JTextArea TxtAreaAu;
    private javax.swing.JTextArea TxtAreaList;
    private javax.swing.JTextField TxtAu;
    private javax.swing.JTextField TxtBorrw;
    private javax.swing.JTextField TxtSearchAu;
    private javax.swing.JTextField TxtSearchTi;
    private javax.swing.JTextField TxtTi;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
