/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package APIs;

import javax.swing.*;
import java.util.*;
import java.io.*;

/**
 *
 * @author jesse
 */
public class QuizAPI extends javax.swing.JFrame {

    ArrayList<Question> theQuestions = new ArrayList<>();
//    List<Question> theQuestions2 = new SubList(0, 15);
    int counter = -1;
    ArrayList<String> choices = new ArrayList<>();
    private int score = 0;
    
    /**
     * Creates new form Quiz
     */
    public QuizAPI() {
        initComponents();
        ButtonGroup buttons = new ButtonGroup();
        buttons.add(RBtnOp1);
        buttons.add(RBtnOp2);
        buttons.add(RBtnOp3);
        buttons.add(RBtnOp4);
//        makeQuestions(BtnNext);
        BtnNext.setVisible(false);
        BtnPrev.setVisible(false);
        BtnSubmit.setVisible(false);
        RBtnOp1.setVisible(false);
        RBtnOp2.setVisible(false);
        RBtnOp3.setVisible(false);
        RBtnOp4.setVisible(false);
        TxtQues.setVisible(false);
        LabNumQues.setVisible(false);
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelScore = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtQues = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        RBtnOp1 = new javax.swing.JRadioButton();
        RBtnOp3 = new javax.swing.JRadioButton();
        RBtnOp2 = new javax.swing.JRadioButton();
        RBtnOp4 = new javax.swing.JRadioButton();
        BtnPrev = new javax.swing.JButton();
        BtnNext = new javax.swing.JButton();
        LabNumQues = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        BtnStart = new javax.swing.JButton();
        LabMess = new javax.swing.JLabel();
        BtnStartOnline = new javax.swing.JButton();

        LabelScore.setText("jLabel2");

        ProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        ProgressBar.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 51, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Here is your score");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));

        BtnSubmit.setBackground(new java.awt.Color(0, 51, 204));
        BtnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        TxtQues.setBackground(new java.awt.Color(255, 255, 255));
        TxtQues.setColumns(20);
        TxtQues.setForeground(new java.awt.Color(0, 0, 0));
        TxtQues.setRows(5);
        jScrollPane1.setViewportView(TxtQues);

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(38, 17));

        RBtnOp1.setBackground(new java.awt.Color(0, 51, 204));
        RBtnOp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RBtnOp1.setForeground(new java.awt.Color(0, 0, 0));

        RBtnOp3.setBackground(new java.awt.Color(0, 51, 204));
        RBtnOp3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RBtnOp3.setForeground(new java.awt.Color(0, 0, 0));

        RBtnOp2.setBackground(new java.awt.Color(0, 51, 204));
        RBtnOp2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RBtnOp2.setForeground(new java.awt.Color(0, 0, 0));

        RBtnOp4.setBackground(new java.awt.Color(0, 51, 204));
        RBtnOp4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RBtnOp4.setForeground(new java.awt.Color(0, 0, 0));

        BtnPrev.setBackground(new java.awt.Color(0, 51, 204));
        BtnPrev.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPrev.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrev.setText("Previous");
        BtnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrevActionPerformed(evt);
            }
        });

        BtnNext.setBackground(new java.awt.Color(0, 51, 204));
        BtnNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnNext.setForeground(new java.awt.Color(255, 255, 255));
        BtnNext.setText("Next");
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        LabNumQues.setPreferredSize(new java.awt.Dimension(40, 16));

        jLabel3.setPreferredSize(new java.awt.Dimension(37, 16));

        TxtName.setBackground(new java.awt.Color(255, 255, 255));
        TxtName.setForeground(new java.awt.Color(0, 0, 0));

        BtnStart.setBackground(new java.awt.Color(0, 0, 204));
        BtnStart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnStart.setForeground(new java.awt.Color(255, 255, 255));
        BtnStart.setText("Start offline");
        BtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartActionPerformed(evt);
            }
        });

        LabMess.setBackground(new java.awt.Color(0, 51, 204));
        LabMess.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabMess.setForeground(new java.awt.Color(0, 0, 0));
        LabMess.setText("Please input your name");

        BtnStartOnline.setText("Start online");
        BtnStartOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartOnlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabNumQues, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnStart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnStartOnline))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnSubmit))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(LabMess)
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(RBtnOp3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(RBtnOp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RBtnOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RBtnOp4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnNext)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSubmit)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabMess)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnStart)
                            .addComponent(BtnStartOnline))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabNumQues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBtnOp1)
                    .addComponent(RBtnOp2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBtnOp3)
                    .addComponent(RBtnOp4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPrev)
                    .addComponent(BtnNext))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        // TODO add your handling code here:
        makeQuestions(BtnNext);
        saveBtnState();
        getBtnState();
    }//GEN-LAST:event_BtnNextActionPerformed

    private void BtnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrevActionPerformed
        // TODO add your handling code here:
        makeQuestions(BtnPrev);
        saveBtnState();
        getBtnState();
    }//GEN-LAST:event_BtnPrevActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        // TODO add your handling code here:
        decideScore();
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel3.setText(String.valueOf(score + " out of 15"));
        saveScore();
        ScorePanel score = new ScorePanel(this);
        score.setVisible(true);

    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void BtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartActionPerformed
        // TODO add your handling code here:
        theQuestions = (ArrayList<Question>) new Question().setQues();
        theQuestions = new ArrayList<>(theQuestions.subList(0, 15));
        makeQuestions(BtnNext);
//        System.out.println(theQuestions.size());
        TxtName.setVisible(false);
        LabMess.setVisible(false);
        BtnStart.setVisible(false);
        BtnNext.setVisible(true);
        BtnPrev.setVisible(true);
        BtnSubmit.setVisible(true);
        RBtnOp1.setVisible(true);
        RBtnOp2.setVisible(true);
        RBtnOp3.setVisible(true);
        RBtnOp4.setVisible(true);
        TxtQues.setVisible(true);
        LabNumQues.setVisible(true);
        jScrollPane1.setVisible(true);
        BtnStartOnline.setVisible(false);
    }//GEN-LAST:event_BtnStartActionPerformed

    private void BtnStartOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartOnlineActionPerformed
        // TODO add your handling code here:
        theQuestions = (ArrayList<Question>) new Question().setQuesOnline();
        makeQuestions(BtnNext);
//        System.out.println(theQuestions.size());
        TxtName.setVisible(false);
        LabMess.setVisible(false);
        BtnStart.setVisible(false);
        BtnStartOnline.setVisible(false);
        BtnNext.setVisible(true);
        BtnPrev.setVisible(true);
        BtnSubmit.setVisible(true);
        RBtnOp1.setVisible(true);
        RBtnOp2.setVisible(true);
        RBtnOp3.setVisible(true);
        RBtnOp4.setVisible(true);
        TxtQues.setVisible(true);
        LabNumQues.setVisible(true);
        jScrollPane1.setVisible(true);
        
        
    }//GEN-LAST:event_BtnStartOnlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizAPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNext;
    private javax.swing.JButton BtnPrev;
    private javax.swing.JButton BtnStart;
    private javax.swing.JButton BtnStartOnline;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JLabel LabMess;
    private javax.swing.JLabel LabNumQues;
    private javax.swing.JLabel LabelScore;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JRadioButton RBtnOp1;
    private javax.swing.JRadioButton RBtnOp2;
    private javax.swing.JRadioButton RBtnOp3;
    private javax.swing.JRadioButton RBtnOp4;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextArea TxtQues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void makeQuestions(JButton b) {
        save();
        if (counter <= 0 && b == BtnPrev) {
            counter = 0;
        } else if (counter == 14 && b == BtnNext) {
            counter = 14;
            JOptionPane.showMessageDialog(rootPane, "That is the end, please press submit.");
        } else if (counter > 0 && b == BtnPrev) {
            counter--;
        } else {
            counter++;
        }
        TxtQues.setText(theQuestions.get(counter).getQues());
        LabNumQues.setText("Question " + (counter + 1) + " of 15");
        RBtnOp1.setText(theQuestions.get(counter).getOption1());
        RBtnOp2.setText(theQuestions.get(counter).getOption2());
        RBtnOp3.setText(theQuestions.get(counter).getOption3());
        RBtnOp4.setText(theQuestions.get(counter).getOption4());

    }

    public void submit() {

    }

    public void save() {
        if (RBtnOp1.isSelected()) {
            choices.add(RBtnOp1.getText());
        } else if (RBtnOp2.isSelected()) {
            choices.add(RBtnOp2.getText());
        } else if (RBtnOp3.isSelected()) {
            choices.add(RBtnOp3.getText());
        } else if (RBtnOp4.isSelected()) {
            choices.add(RBtnOp4.getText());
        }
    }

    public void saveBtnState() {
        try {
            FileWriter writ = new FileWriter("btnState.txt", true);
        if (RBtnOp1.isSelected()) {
            writ.write("RBtnOp1 " + String.valueOf(this.counter) + "\n");
            writ.close();
        } else if (RBtnOp2.isSelected()) {
            writ.write("RBtnOp2 " + String.valueOf(this.counter) + "\n");
            writ.close();
        } else if (RBtnOp3.isSelected()) {
            writ.write("RBtnOp3 " + String.valueOf(this.counter) + "\n");
            writ.close();
        } else {
            writ.write("RBtnOp4 " + String.valueOf(this.counter) + "\n");
            writ.close();
        }
        
        } catch (Exception e) {
        }
    }
    
    public void getBtnState() {
        String line;
        String[] lines;
        try {
            BufferedReader buff = new BufferedReader(new FileReader("btnState.txt"));
            
            while ((line = buff.readLine()) != null) {
                lines = line.split(" ");
                if (Integer.valueOf(lines[1]) == this.counter) {
                   JRadioButton RBtn = new JRadioButton(lines[0]);
                   RBtn.setSelected(true);
                }
            }
        } catch (Exception e) {
        }
    }
    
    public void decideScore() {

        for (int i = 0; i < choices.size(); i++) {
            if (choices.get(i).equals(theQuestions.get(i).getAns())) {
                score++;
            }
        }
/*
        for (String thing : choices) {
            System.out.println(thing);
        }
        System.out.println();
        System.out.println();
*/
        for (Question thing2 : theQuestions) {
            System.out.println(thing2.getAns());
        }

    }

    public int getScore() {
        return score;
    }

    public void saveScore() {

        try {
            FileWriter writ = new FileWriter("scores.txt", true);
            writ.write(TxtName.getText() + " ");
            writ.write(String.valueOf(this.score) + "\n");
            writ.close();
        } catch (Exception e) {
        }
    }
}
