/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.houghton.csci218.swingpractice;

/**
 *
 * @author jesse
 */
public class TempConverter extends javax.swing.JFrame {
    double temp;
    String formatTemp;
    /**
     * Creates new form TempConverter
     */
    public TempConverter() {
        initComponents();
        javax.swing.ButtonGroup TempFrom = new javax.swing.ButtonGroup();
        TempFrom.add(FarenFrom);
        TempFrom.add(CelFrom);
        TempFrom.add(KelFrom);
        
        javax.swing.ButtonGroup TempTo = new javax.swing.ButtonGroup();
        TempTo.add(FarenTo);
        TempTo.add(CelTo);
        TempTo.add(KelTo);
        
        TxtEndTemp.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FarenFrom = new javax.swing.JRadioButton();
        CelFrom = new javax.swing.JRadioButton();
        KelFrom = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtTemp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FarenTo = new javax.swing.JRadioButton();
        CelTo = new javax.swing.JRadioButton();
        KelTo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        TxtEndTemp = new javax.swing.JTextField();

        jRadioButton4.setText("jRadioButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Convert from:");

        FarenFrom.setBackground(new java.awt.Color(0, 51, 204));
        FarenFrom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FarenFrom.setForeground(new java.awt.Color(0, 0, 0));
        FarenFrom.setText("Fahrenheit");

        CelFrom.setBackground(new java.awt.Color(0, 51, 204));
        CelFrom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CelFrom.setForeground(new java.awt.Color(0, 0, 0));
        CelFrom.setText("Celsius");

        KelFrom.setBackground(new java.awt.Color(0, 51, 204));
        KelFrom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        KelFrom.setForeground(new java.awt.Color(0, 0, 0));
        KelFrom.setText("Kelvin");
        KelFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelFromActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 51, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Enter Numeric Temperture");

        TxtTemp.setBackground(new java.awt.Color(255, 255, 255));
        TxtTemp.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(0, 51, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Convert to:");

        FarenTo.setBackground(new java.awt.Color(0, 51, 204));
        FarenTo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FarenTo.setForeground(new java.awt.Color(0, 0, 0));
        FarenTo.setText("Fahrenheit");
        FarenTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FarenToActionPerformed(evt);
            }
        });

        CelTo.setBackground(new java.awt.Color(0, 51, 204));
        CelTo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CelTo.setForeground(new java.awt.Color(0, 0, 0));
        CelTo.setText("Celsius");
        CelTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelToActionPerformed(evt);
            }
        });

        KelTo.setBackground(new java.awt.Color(0, 51, 204));
        KelTo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        KelTo.setForeground(new java.awt.Color(0, 0, 0));
        KelTo.setText("Kelvin");
        KelTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelToActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 51, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Compareable Temperture is:");

        TxtEndTemp.setBackground(new java.awt.Color(255, 255, 255));
        TxtEndTemp.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTemp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(FarenTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CelTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KelTo))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(FarenFrom)
                                .addGap(18, 18, 18)
                                .addComponent(CelFrom)
                                .addGap(18, 18, 18)
                                .addComponent(KelFrom))
                            .addComponent(jLabel5))
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addComponent(TxtEndTemp))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FarenFrom)
                    .addComponent(CelFrom)
                    .addComponent(KelFrom))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FarenTo)
                    .addComponent(CelTo)
                    .addComponent(KelTo))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtEndTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KelFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelFromActionPerformed

    private void KelToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelToActionPerformed
        // TODO add your handling code here:
        convert();
        
    }//GEN-LAST:event_KelToActionPerformed

    private void FarenToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FarenToActionPerformed
        // TODO add your handling code here:
        convert();
        
        
    }//GEN-LAST:event_FarenToActionPerformed

    private void CelToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelToActionPerformed
        // TODO add your handling code here:
        convert();
        
    }//GEN-LAST:event_CelToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CelFrom;
    private javax.swing.JRadioButton CelTo;
    private javax.swing.JRadioButton FarenFrom;
    private javax.swing.JRadioButton FarenTo;
    private javax.swing.JRadioButton KelFrom;
    private javax.swing.JRadioButton KelTo;
    private javax.swing.JTextField TxtEndTemp;
    private javax.swing.JTextField TxtTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables

    public void convert() {
        if (FarenFrom.isSelected() && FarenTo.isSelected()) {
            formatTemp = String.format("%.2f", Double.valueOf(TxtTemp.getText()));
            TxtEndTemp.setText(formatTemp);
        } else if (FarenFrom.isSelected() && CelTo.isSelected()) {
            temp = (5.0 / 9.0) * (Double.valueOf(TxtTemp.getText()) - 32);
            formatTemp = String.format("%.2f", temp);
            TxtEndTemp.setText(formatTemp);
        } else if (FarenFrom.isSelected() && KelTo.isSelected()) {
            temp = (5.0 / 9.0) * (Double.valueOf(TxtTemp.getText()) - 32) + 273.15;
            formatTemp = String.format("%.2f", temp);
            TxtEndTemp.setText(formatTemp);
        } else if (CelFrom.isSelected() && CelTo.isSelected()) {
            formatTemp = String.format("%.2f", Double.valueOf(TxtTemp.getText()));
            TxtEndTemp.setText(formatTemp);
        } else if (CelFrom.isSelected() && FarenTo.isSelected()) {
            temp = (Double.valueOf(TxtTemp.getText()) * 9 / 5) + 32;
            formatTemp = String.format("%.2f", temp);
            TxtEndTemp.setText(formatTemp);
        } else if (CelFrom.isSelected() && KelTo.isSelected()) {
            temp = Double.valueOf(TxtTemp.getText()) + 273.15;
            formatTemp = String.format("%.2f", temp);
            TxtEndTemp.setText(formatTemp);
        } else if (KelFrom.isSelected() && KelTo.isSelected()) {
            formatTemp = String.format("%.2f", Double.valueOf(TxtTemp.getText()));
            TxtEndTemp.setText(formatTemp);
        } else if (KelFrom.isSelected() && FarenTo.isSelected()) {
            temp = (Double.valueOf(TxtTemp.getText()) - 273.15) * 9 / 5 + 32;
            formatTemp = String.format("%.2f", temp);
            TxtEndTemp.setText(formatTemp);
        } else if (KelFrom.isSelected() && CelTo.isSelected()) {
            temp = Double.valueOf(TxtTemp.getText()) - 273.15;
            formatTemp = String.format("%.2f", temp);
            TxtEndTemp.setText(formatTemp);
        }
    }
        
    

}
