/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTac;

/**
 *
 * @author jesse
 */
public class TicTacToeGUI extends javax.swing.JFrame {
    TicTacToe game;
    int count = 0;
    int countO = 0;
    int countTie = 0;
    /**
     * Creates new form TicTacToeGUI
     */
    public TicTacToeGUI() {
        Board board = new Board(3);
        Player player1 = new Player("bob", "X");
        Player player2 = new Player("tim", "O");
        game = new TicTacToe(player1, player2, board, player1);
        initComponents();
        BtnYes.setVisible(false);
        BtnNo.setVisible(false);
        Ques.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Winner = new javax.swing.JLabel();
        Owins = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn7 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CurrPlay = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Owins2 = new javax.swing.JLabel();
        Xwins = new javax.swing.JLabel();
        BtnYes = new javax.swing.JButton();
        BtnNo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LabelTies = new javax.swing.JLabel();
        LabelVic = new javax.swing.JLabel();
        Ques = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel6.setText("jLabel6");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        Winner.setBackground(new java.awt.Color(0, 0, 204));
        Winner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Winner.setForeground(new java.awt.Color(0, 0, 0));
        Winner.setText("string");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Owins.setBackground(new java.awt.Color(0, 0, 255));
        Owins.setPreferredSize(new java.awt.Dimension(600, 438));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TIC-TAC-TOE");

        Btn7.setBackground(new java.awt.Color(0, 0, 0));
        Btn7.setForeground(new java.awt.Color(255, 255, 255));
        Btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn7MouseClicked(evt);
            }
        });

        Btn1.setBackground(new java.awt.Color(0, 0, 0));
        Btn1.setForeground(new java.awt.Color(255, 255, 255));
        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn1MouseClicked(evt);
            }
        });

        Btn2.setBackground(new java.awt.Color(0, 0, 0));
        Btn2.setForeground(new java.awt.Color(255, 255, 255));
        Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn2MouseClicked(evt);
            }
        });

        Btn3.setBackground(new java.awt.Color(0, 0, 0));
        Btn3.setForeground(new java.awt.Color(255, 255, 255));
        Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn3MouseClicked(evt);
            }
        });

        Btn5.setBackground(new java.awt.Color(0, 0, 0));
        Btn5.setForeground(new java.awt.Color(255, 255, 255));
        Btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn5MouseClicked(evt);
            }
        });

        Btn9.setBackground(new java.awt.Color(0, 0, 0));
        Btn9.setForeground(new java.awt.Color(255, 255, 255));
        Btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn9MouseClicked(evt);
            }
        });

        Btn8.setBackground(new java.awt.Color(0, 0, 0));
        Btn8.setForeground(new java.awt.Color(255, 255, 255));
        Btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn8MouseClicked(evt);
            }
        });

        Btn4.setBackground(new java.awt.Color(0, 0, 0));
        Btn4.setForeground(new java.awt.Color(255, 255, 255));
        Btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn4MouseClicked(evt);
            }
        });

        Btn6.setBackground(new java.awt.Color(0, 0, 0));
        Btn6.setForeground(new java.awt.Color(255, 255, 255));
        Btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn6MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Next Player");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setOpaque(true);

        CurrPlay.setText("string");

        jLabel8.setBackground(new java.awt.Color(0, 0, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Number of wins: \"X\"");

        jLabel11.setBackground(new java.awt.Color(0, 0, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Number of wins: \"O\"");

        Owins2.setText("int");

        Xwins.setText("int");

        BtnYes.setBackground(new java.awt.Color(0, 51, 255));
        BtnYes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnYes.setForeground(new java.awt.Color(255, 255, 255));
        BtnYes.setText("Yes");
        BtnYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnYesMouseClicked(evt);
            }
        });

        BtnNo.setBackground(new java.awt.Color(0, 51, 255));
        BtnNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnNo.setForeground(new java.awt.Color(255, 255, 255));
        BtnNo.setText("No");
        BtnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNoMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Number of ties");

        LabelTies.setText("int");

        LabelVic.setBackground(new java.awt.Color(0, 0, 255));
        LabelVic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelVic.setForeground(new java.awt.Color(0, 0, 0));
        LabelVic.setText("S");

        Ques.setBackground(new java.awt.Color(0, 0, 255));
        Ques.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ques.setForeground(new java.awt.Color(0, 0, 0));
        Ques.setText("Play again?");

        javax.swing.GroupLayout OwinsLayout = new javax.swing.GroupLayout(Owins);
        Owins.setLayout(OwinsLayout);
        OwinsLayout.setHorizontalGroup(
            OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwinsLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(113, 113, 113)
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OwinsLayout.createSequentialGroup()
                        .addComponent(Btn8)
                        .addGap(107, 107, 107)
                        .addComponent(Btn9))
                    .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(OwinsLayout.createSequentialGroup()
                            .addComponent(Btn2)
                            .addGap(107, 107, 107)
                            .addComponent(Btn3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OwinsLayout.createSequentialGroup()
                            .addComponent(Btn5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn6)))))
            .addGroup(OwinsLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OwinsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CurrPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OwinsLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Xwins, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelVic, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OwinsLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Owins2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OwinsLayout.createSequentialGroup()
                        .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ques)
                            .addGroup(OwinsLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(BtnYes)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnNo))))
            .addGroup(OwinsLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelTies, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        OwinsLayout.setVerticalGroup(
            OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwinsLayout.createSequentialGroup()
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OwinsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelVic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CurrPlay))
                        .addGap(18, 18, 18))
                    .addGroup(OwinsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Ques)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BtnYes)
                            .addComponent(BtnNo))
                        .addGap(30, 30, 30)))
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OwinsLayout.createSequentialGroup()
                        .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OwinsLayout.createSequentialGroup()
                        .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(Owins2)
                    .addComponent(Xwins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OwinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LabelTies))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Owins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Owins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseClicked
        // TODO add your handling code here:
        if (Btn1.getText().equals("")) {
            Btn1.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn1MouseClicked

    private void Btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseClicked
        // TODO add your handling code here:
        if (Btn2.getText().equals("")) {
            Btn2.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn2MouseClicked

    private void Btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseClicked
        // TODO add your handling code here:
        if (Btn3.getText().equals("")) {
            Btn3.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn3MouseClicked

    private void Btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn4MouseClicked
        // TODO add your handling code here:
        if (Btn4.getText().equals("")) {
            Btn4.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn4MouseClicked

    private void Btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseClicked
        // TODO add your handling code here:
        if (Btn5.getText().equals("")) {
            Btn5.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn5MouseClicked

    private void Btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseClicked
        // TODO add your handling code here:
        if (Btn6.getText().equals("")) {
            Btn6.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn6MouseClicked

    private void Btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn7MouseClicked
        // TODO add your handling code here:
        if (Btn7.getText().equals("")) {
            Btn7.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn7MouseClicked

    private void Btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn8MouseClicked
        // TODO add your handling code here:
        if (Btn8.getText().equals("")) {
            Btn8.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn8MouseClicked

    private void Btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn9MouseClicked
        // TODO add your handling code here:
        if (Btn9.getText().equals("")) {
            Btn9.setText(game.currentPlayer.getSymbol());
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        } if (checkWinnerGUI("X")) {
           
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Xwins.setText(String.valueOf(++count));
            LabelVic.setText("X wins");
            
        } else if (checkWinnerGUI("O")) {
            
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
            Owins2.setText(String.valueOf(++countO)); 
            LabelVic.setText("O wins");
            
        } else if (full()) {
            
            LabelTies.setText(String.valueOf(++countTie));
            BtnYes.setVisible(true);
            BtnNo.setVisible(true);
            Ques.setVisible(true);
        }
    }//GEN-LAST:event_Btn9MouseClicked

    private void BtnYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnYesMouseClicked
        // TODO add your handling code here:
        restart();
    }//GEN-LAST:event_BtnYesMouseClicked

    private void BtnNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNoMouseClicked
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_BtnNoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnNo;
    private javax.swing.JButton BtnYes;
    private javax.swing.JLabel CurrPlay;
    private javax.swing.JLabel LabelTies;
    private javax.swing.JLabel LabelVic;
    private javax.swing.JPanel Owins;
    private javax.swing.JLabel Owins2;
    private javax.swing.JLabel Ques;
    private javax.swing.JLabel Winner;
    private javax.swing.JLabel Xwins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
public boolean checkWinnerGUI(String symbol) {
        if (Btn7.getText().equals(symbol) && Btn8.getText().equals(symbol) && Btn9.getText().equals(symbol)) {
            return true;
        } else if (Btn4.getText().equals(symbol) && Btn5.getText().equals(symbol) && Btn6.getText().equals(symbol)) {
            return true;
        } else if (Btn1.getText().equals(symbol) && Btn2.getText().equals(symbol) && Btn3.getText().equals(symbol)) {
            return true;
        } else if (Btn7.getText().equals(symbol) && Btn4.getText().equals(symbol) && Btn1.getText().equals(symbol)) {
            return true;
        } else if (Btn8.getText().equals(symbol) && Btn5.getText().equals(symbol) && Btn2.getText().equals(symbol)) {
            return true;
        } else if (Btn9.getText().equals(symbol) && Btn6.getText().equals(symbol) && Btn3.getText().equals(symbol)) {
            return true;
        } else if (Btn7.getText().equals(symbol) && Btn5.getText().equals(symbol) && Btn3.getText().equals(symbol)) {
            return true;
        } else if (Btn9.getText().equals(symbol) && Btn5.getText().equals(symbol) && Btn1.getText().equals(symbol)) {
            return true;
        } else {
            return false;
        }
    }
    public void restart() {
        Btn1.setText("");
        Btn2.setText("");
        Btn3.setText("");
        Btn4.setText("");
        Btn5.setText("");
        Btn6.setText("");
        Btn7.setText("");
        Btn8.setText("");
        Btn9.setText("");
        LabelVic.setText("");
        BtnYes.setVisible(false);
        BtnNo.setVisible(false);
        Ques.setVisible(false);
        if (game.currentPlayer.getSymbol().equals(game.player2.getSymbol())) {
            game.switchPlayer();
            CurrPlay.setText(game.currentPlayer.getSymbol());
        }
    }
    public boolean full() {
        String[] BtnTxt = {Btn1.getText(), Btn2.getText(), Btn3.getText(), Btn4.getText(), Btn5.getText(), Btn6.getText(), Btn7.getText(), Btn8.getText(), Btn9.getText(),};
        for (String txt : BtnTxt) {
            if (txt.equals("")) {
                return false;
            }
        }
        return true;
    }
}